controllers:
  resource: ../src/Controller/
  type: attribute

home:
  path: /admin/home
  controller: App\Controller\admin\AdminControllerHomeController::home

app_admin:
  path: /admin/utilisateurs
  controller: app\Controller\admin\AdminController::editUser

app_admin_permission:
  path: /admin/permission
  controller: app\Controller\admin\AdminPermissionController::editPermission
